### ISSUE TITLE
TODO items after glvis-4.3

### ISSUE THREAD

**Issue by tzanio** [GLVis/glvis#304]
**After the release:**

- [ ] Add style check to PR CIs
- [ ]  #241
- [x] new bugfix release `glvis-4.3.2` (https://github.com/GLVis/glvis/pull/317)
- [x] Notarize the Mac binary?
- [x] #316 ( #311)
- [x] Update [pyglvis](https://github.com/GLVis/pyglvis/) (Merge https://github.com/GLVis/pyglvis/pull/44)
- [x] #310 
- [x] #309 (#308)
- [x] #307
- [x] #296
- [x] Update the Mac binary
- [x] Update [glvis-js](https://github.com/GLVis/glvis-js) and [glvis.org/live](https://glvis.org/live/) (DO THIS BEFORE pyglvis)

**Comment by tzanio** [comment]
See also

⚫ **Postponed:**
- #289 (see #268)
- #291
- #272
- #274
- #232 
- #170
- #166
- #133
- Support for visualization of particle data
- Adaptive geometry refiner
- Raytracing?!
- Better vector graphics output
- Improved testing with random keys
